### PR TITLE
Replace unmaintained css package by @adobe/css-tools

### PR DESCRIPTION
**Pull request by holblin**

### CODE REVIEW

**Comment by holblin** [comment]
Hi @bezoerb 👋
I noticed that you used an unmaintained package.
Do you mind reviewing and merging that PR (and if possible with a new `npm publish`)?

**Comment by holblin** [comment]
Ref: https://github.com/reworkcss/css/issues/164

**Comment by bezoerb** [comment]
Thanks 😊

**Comment by bezoerb** [comment]
i created a second PR without conflicts :)
See #308
Thanks again @holblin

**Comment by bezoerb** [comment]
New version: [v11.0.1](https://github.com/bezoerb/inline-critical/releases/tag/v11.0.1)

**Pull request closed without merging**
