### PR TITLE
Support minifying extracted css

### PR DESCRIPTION
**Pull request by GeorgeTaveras1231**
This allows users to receive minified extracted CSS.

Notes
===
- The testing strategy for some of the existing tests should be revisited. For example, this expectation passes regardless of whether the code extracts the css or not: https://github.com/bezoerb/inline-critical/blob/master/test/index.js#L80

### CODE REVIEW

**Comment by bezoerb** [comment]
Awesome!
Thanks @GeorgeTaveras1231
And thanks for the hint on the tests. I’ll have a look in the next days.

**Comment by GeorgeTaveras1231** [comment]
@bezoerb can you give me a heads up when this is published?

**Comment by GeorgeTaveras1231** [comment]
@bezoerb any update on this?

**Comment by bezoerb** [comment]
@GeorgeTaveras1231: https://github.com/bezoerb/inline-critical/releases/tag/v4.0.3

**Pull request merged**
