### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by XhmikosR**
Also move `fs-extra` to devDependencies and remove snyk and yarn.lock.

@bezoerb: I personally don't see any need for snyk at this point hence why I removed it. I'd say you should remove it from the repo. I also don't use yarn and having to maintain two lock files seems unneeded effort.

Let me know if you want me to make any changes. The branch as is now doesn't have any known npm vulnerabilities and has much less packages.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Oh and perhaps remove the obsolete branches here and in asset-resolver and postcss-image-inliner :)

**Comment by bezoerb** [comment]
Thanks @XhmikosR :)
i'm totally fine with removing snyk & yarn.lock

**Comment by XhmikosR** [comment]
@bezoerb: can you please release a new patch version for master?

**Comment by bezoerb** [comment]
Done. [v5.2.2](https://github.com/bezoerb/inline-critical/releases/tag/v5.2.2)

**Pull request merged**
